name: Build Magica Manager
on:
  workflow_dispatch:

jobs:
  build-manager:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./manager

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Patch UI for Magica Exploit
        run: |
          # Force 'Jailbreak' button visibility and enablement
          find app/src/main/java -name "HomeMaterial.kt" -exec sed -i 's/if (KSUD_INSTALLED)/if (true)/g' {} +
          find app/src/main/java -name "HomeViewModel.kt" -exec sed -i 's/val isGki = .*/val isGki = true/g' {} +
          find app/src/main/java -name "InstallScreen.kt" -exec sed -i 's/if (isGki)/if (true)/g' {} +
          
          # Force 'Next' button enablement, default method, and dummy partition
          find app/src/main/java -name "InstallScreen.kt" -exec sed -i 's/mutableStateOf<InstallMethod?> (null)/mutableStateOf<InstallMethod?>(InstallMethod.DirectInstall)/g' {} +
          find app/src/main/java -name "InstallScreen.kt" -exec sed -i '/onNext = {/,/}/c\        onNext = { onInstall() },' {} +
          find app/src/main/java -name "InstallScreen.kt" -exec sed -i 's/initialValue = emptyList())/initialValue = listOf("boot"))/g' {} +
          find app/src/main/java -name "InstallScreen.kt" -exec sed -i 's/getAvailablePartitions()/getAvailablePartitions().ifEmpty { listOf("boot") }/g' {} +
          find app/src/main/java -name "InstallMaterial.kt" -exec sed -i 's/enabled = uiState.installMethod != null/enabled = true/g' {} +
          find app/src/main/java -name "InstallMiuix.kt" -exec sed -i 's/enabled = uiState.installMethod != null/enabled = true/g' {} +

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Build with Gradle
        run: ./gradlew :app:assembleDebug

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Magica-KernelSU-Manager
          path: manager/app/build/outputs/apk/debug/*.apk
